import { beforeEach, describe, expect, it } from "vitest";
import { scopePaths, useAnnotationStore as store } from "./useAnnotationStore";
const images = ["a", "b", "c", "d"].map((path) => ({ path, name: path }));
const get = store.getState;
beforeEach(() => {
  get().setImages(images);
  get().select("a");
  get().replaceAnnotations({}, []);
  get().setFrameIndices({});
});
describe("selection and scope", () => {
  it("clamps navigation and retains search order until explicitly exited", () => {
    get().pushScope({ kind: "search", ids: ["b", "d", "b", "missing"], label: "search" });
    expect(scopePaths(get())).toEqual(["b", "d"]);
    get().selectAdjacent(-1);
    expect(get().selectedPath).toBe("b");
    get().selectAdjacent(1);
    expect(get().selectedPath).toBe("d");
    get().selectAdjacent(1);
    expect(get().selectedPath).toBe("d");
    get().pushScope({ kind: "video", ids: ["d"], label: "video" });
    get().popScope();
    expect(get().scopeStack).toHaveLength(2);
    get().popScope();
    get().selectAdjacent(-1);
    expect(get().selectedPath).toBe("c");
    get().popScope();
    expect(get().scopeStack).toEqual([{ kind: "project" }]);
  });
  it("handles empty scopes, replacements, invalid selection and selecting outside a scope", () => {
    get().select("missing");
    expect(get().selectedPath).toBe("a");
    get().pushScope({ kind: "search", ids: ["b"], label: "one" });
    get().pushScope({ kind: "search", ids: [], label: "empty" });
    expect(get().scopeStack).toHaveLength(2);
    expect(get().selectedPath).toBe("");
    get().selectAdjacent(1);
    get().selectUnannotated(-1);
    expect(get().selectedPath).toBe("");
    expect(get().scopeStack).toHaveLength(2);
    get().popScope();
    expect(get().selectedPath).toBe("a");
    get().pushScope({ kind: "video", ids: ["b"], label: "one" });
    get().pushScope({ kind: "search", ids: ["b"], label: "nested" });
    expect(get().scopeStack).toHaveLength(3);
    get().select("d");
    expect(get().scopeStack).toHaveLength(1);
    get().setImages([]);
    expect(get().selectedPath).toBe("");
  });
  it("searches unannotated paths within the active scope", () => {
    get().replaceAnnotations({ b: [{ id: "s", type: "point", labelId: "l", points: [1, 2] }] }, [
      { id: "l", name: "l", color: "#fff", shapeType: "any" },
    ]);
    get().pushScope({ kind: "search", ids: ["a", "b", "d"], label: "results" });
    get().selectUnannotated(1);
    expect(get().selectedPath).toBe("d");
    get().selectUnannotated(1);
    expect(get().selectedPath).toBe("d");
    get().selectUnannotated(-1);
    expect(get().selectedPath).toBe("a");
    store.setState({ selectedPath: "missing" });
    get().selectUnannotated(-1);
    expect(get().selectedPath).toBe("d");
    store.setState({ selectedPath: "missing" });
    get().selectAdjacent(1);
    expect(get().selectedPath).toBe("a");
    store.setState({ selectedPath: "missing" });
    get().selectAdjacent(-1);
    expect(get().selectedPath).toBe("d");
  });
  it("deletes and resumes atomically, pruning frame metadata, annotations and history", () => {
    get().addAnnotation("d", { id: "s", type: "point", labelId: "l", points: [1, 2] });
    get().select("d");
    get().selectShape("s");
    get().setFrameIndices({ d: 3 });
    const snapshots: string[] = [];
    const unsub = store.subscribe((state) => snapshots.push(state.selectedPath));
    get().removeImages(["d"]);
    unsub();
    expect(snapshots).toEqual(["c"]);
    expect(get().images).toHaveLength(3);
    expect(get().annotationsByImage.d).toBeUndefined();
    expect(get().undoStack).toEqual([]);
    expect(get().selectedShapeId).toBeNull();
    expect(get().frameIndices).toEqual({});
    get().removeImages(["a"]);
    expect(get().selectedPath).toBe("c");
    store.setState({ selectedPath: "missing" });
    get().removeImages(["missing"]);
    expect(get().selectedPath).toBe("b");
    get().removeImages(["b", "c"]);
    expect(get().selectedPath).toBe("");
  });
  it("continues within search results and exits an exhausted scope", () => {
    get().pushScope({ kind: "search", ids: ["b", "d"], label: "results" });
    get().removeImages(["b"]);
    expect(get().selectedPath).toBe("d");
    get().removeImages(["d"]);
    expect(get().selectedPath).toBe("a");
    expect(get().scopeStack).toHaveLength(1);
  });
});
