// Developer-only UI verification harness, never imported by the application.
// TODO(annotool): IPC is mocked here intentionally; responses are REAL inspection
// output generated by verify-onnx-graph.py, not fabricated model data.
import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { mockIPC } from "@tauri-apps/api/mocks";
import { OnnxGraphDialog } from "../src/components/settings/OnnxGraphDialog";
import { ONNX_GRAPH_ZH_CN as text } from "../src/i18n/onnx-graph.zh-CN";
import "../src/App.css";

mockIPC(async (command, args) => {
  if (command !== "inspect_onnx_graph" || !args || typeof args !== "object" || !("path" in args))
    throw new Error(command);
  const name = args.path === "yolov8n.onnx" ? "yolov8n" : "yolo11n";
  const response = await fetch(`/.local-models/${name}.graph.json`);
  if (!response.ok) throw new Error(text.previewMissing);
  return response.json();
});
function Preview() {
  const [path, setPath] = useState<string | null>("yolo11n.onnx");
  return (
    <main className="min-h-screen bg-slate-950 p-5 text-slate-200">
      <p>{text.previewTitle}</p>
      {["yolo11n.onnx", "yolov8n.onnx"].map((name) => (
        <button key={name} className="m-3 rounded border p-2" onClick={() => setPath(name)}>
          {name}
        </button>
      ))}
      {path && <OnnxGraphDialog path={path} onClose={() => setPath(null)} />}
    </main>
  );
}
createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <Preview />
  </React.StrictMode>,
);
